name: "综合 Bug 反馈 | Comprehensive Bug"
description: |
  遇见了没有细分选项的其他 Bug。
  Encountered bugs that do not fall under specific categories.
type: "Bug"
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: 检查项 Checklist
    description: |
      请逐个检查下列项目，并勾选确认。
      Please review each of the following items individually and check to confirm.
    options:
    - label: |
        我已在 [Issues 页面](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。"
        I have searched the [Issues page](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+) and the [Common & Hard-to-Diagnose Feedback and Issue List](https://github.com/Hex-Dragon/PCL2/discussions/1930) to confirm that this bug has not been submitted before.
      required: true
    - label: |
        我确认正在使用的启动器版本为 Fast Ring 通道的最新版。（最新版获取方式：启动器 `设置-其他-系统` 切换至 Fast Ring 通道并单击“检查更新”，或在 [Releases](https://github.com/PCL-Community/PCL2-CE/releases) 页面的最顶部直接下载）
        I confirm that I am using the latest version of the launcher from the Fast Ring channel. (To get the latest version: switch to the Fast Ring channel in the launcher's `Settings - Other - System` and click "Check for Updates", or download directly from the top of the [Releases](https://github.com/PCL-Community/PCL2-CE/releases) page.)
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述 Description
    description: |
      详细描述该 Bug 的具体表现。
      Provide a detailed description of the specific behavior of the bug.
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 重现步骤 Steps to Reproduce
    description: |
      详细描述要怎么操作才能再次触发这个 Bug。
      Provide a detailed description of the steps required to reproduce this bug.
    value: |
      1、点击xxxx
      2、往下滚，然后点击xxxx
      1. Click xxxx
      2. Scroll down, and click xxxx
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 日志与附件 Logs & Attachments
    description: |
      上传启动器同目录下的 PCL/Log 文件夹中的按照日期排序最新的日志文件
      Please upload the most recent log file from the PCL/Log folder in the launcher directory, sorted by date.
    placeholder: |
      先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。
      Click on this text box first, then drag and drop the files directly into the text box to upload them.
  validations:
    required: true
