name: "新功能提案 | Feature Request"
description: |
  对已有功能的大幅度修改，或添加一个新内容或选项。但根据情况，社区版很可能不会处理这个 Issue，而是会将其转交给官方版进一步评估。
  Requests for significant modifications to existing features or the addition of new content or options. However, depending on the situation, the Community Edition may not process this issue and will instead forward it to the official version for further evaluation.
type: "新功能"
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: 检查项 Checklist
    description: |
      请逐个检查下列项目，并勾选确认。
      Please review each of the following items individually and check to confirm.
    options:
    - label: |
        我已在 [官方版 Issues 页面](https://github.com/Meloong-Git/PCL2/issues?q=is%3Aissue+) 和 [官方版功能投票页面](https://github.com/Meloong-Git/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/) 中搜索，已确认官方版不计划处理这个内容。
        I have searched the [official version's Issues page](https://github.com/Meloong-Git/PCL2/issues?q=is%3Aissue+) and the [official version's feature voting page](https://github.com/Meloong-Git/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/), and confirmed that the official version does not plan to address this content.
    - label: |
        我已在 [社区版 Issues 页面](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+) 中搜索，确认了这一建议未在社区版被提交过。
        I have searched the [Community Edition's Issues page](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+), and confirmed that this suggestion has not been submitted in the Community Edition.
      required: true
    - label: |
        我仍想要提交，是因为我确认这个 Issue 是官方版转交过来，或是希望由社区版处理的。
        I still want to submit this because I confirm that this issue has been forwarded from the official version or is intended to be handled by the Community Edition.
      required: true
    - label: |
        我已知悉社区不对这类 Issue 的完成时间作出任何保证，并有足够的耐心等待社区开发者的处理，同时已知悉如果我作出催促、质问或类似的举动，这个 Issue 可能会被直接关闭
        I acknowledge that the community does not guarantee the completion time for such issues, and I have sufficient patience to wait for the community developers to address it. I also understand that if I make any demands, inquiries, or similar actions, this issue may be closed immediately.
      required: true
- type: input
  id: "yml-2"
  attributes:
    label: "官方版原 Issue 编号 | Original Issue Number in Official Version"
    description: |
      如果这个 Issue 是从官方版转交过来的，请将原 Issue 标题旁的**编号**输入到下方预设文本的`#`后，不要输入任何其他非数字字符。若不是，请清空下方输入框。
      If this issue has been forwarded from the official version, please enter the **number** next to the original issue title in the preset text below after the `#`, without entering any other non-numeric characters. If not, please clear the input box below.
    value: "- Meloong-Git/PCL2#"
- type: textarea
  id: "yml-3"
  attributes:
    label: "官方版原 Issue 编号 | Original Issue Number in Official Version"
    description: |
      如果这个 Issue 是从官方版转交过来的，请将原 Issue 标题旁的**编号**输入到下方预设文本的`#`后，不要输入任何其他非数字字符。若不是，请清空下方输入框。
      If this issue has been forwarded from the official version, please enter the **number** next to the original issue title in the preset text below after the `#`, without entering any other non-numeric characters. If not, please clear the input box below.
    value: "- Meloong-Git/PCL2#"
- type: textarea
  id: "yml-3"
  attributes:
    label: 描述 | Description
    description: |
      详细描述你想添加的功能具体是怎样的。
      Provide a detailed description of the specific functionality you want to add.
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 原因 Reason
    description: |
      详细描述你为什么需要这项功能，这有助于开发者评估它的优先度。
      Provide a detailed explanation of why you need this feature. This will help the developers assess its priority.
    value: |
      （示例）
      我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
      (Sample)  
      I need this feature to xxxx. Many people have the need for xxxx, but without this feature, they won't be able to xxxx.
  validations:
    required: true
