name: release-beta_publish

on:
  release:
    types: [published]

jobs:
  build:
    if: ${{ github.event.release.prerelease }}
    strategy:
      matrix:
        include:
          - configuration: Beta
            architecture: x64
            os: windows-latest
          - configuration: Beta
            architecture: ARM64
            os: windows-latest
      fail-fast: false

    uses: ./.github/workflows/reusable-build.yml
    with:
      configuration: ${{ matrix.configuration }}
      architecture: ${{ matrix.architecture }}
    secrets: inherit

  changelog:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ github.event.release.prerelease }}
    steps:
      - name: Checkout all
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install changelogithub

      - name: Generate Changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rename_and_release:
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - configuration: Beta
            architecture: x64
          - configuration: Beta
            architecture: ARM64
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: PCL2_CE_${{ matrix.configuration }}_${{ matrix.architecture }}
          path: ./artifact

      - name: Rename binaries
        run: |
          mv "./artifact/Plain Craft Launcher 2.exe" "PCL2_CE_${{ matrix.configuration }}_${{ matrix.architecture }}.exe"

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: |
            PCL2_CE_${{ matrix.configuration }}_${{ matrix.architecture }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger MirrorChyanUploading
        shell: bash
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_uploading -f channel=beta -f arch=${{ matrix.architecture == 'x64' && 'x64' || 'arm64' }}
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
