name: Update Help.zip

on:
  workflow_dispatch:

jobs:
  update-help:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update Help
      run: |
        cd ..
        git clone https://github.com/PCL-Community/PCL2CEHelp -b master --single-branch --depth 1
        cd PCL2CEHelp
        rm -Force -r *.*
        Compress-Archive -Path .\* -DestinationPath .\Help.zip
        Copy-Item -Path .\Help.zip -Destination "${{ github.workspace }}\Plain Craft Launcher 2\Resources\Help.zip" -Force
        cd ..
        rm -Force -r .\PCL2CEHelp
        cd ${{ GITHUB.WORKSPACE }}

    - name: Commit Files
      run: |
        chcp 65001 >nul
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "chore: 更新帮助库"

    - name: Push to GitHub
      uses: ad-m/github-push-action@master
